- name: Configuração da minha VM
  hosts: vm 
  become: yes

  tasks:
    
  - name: inclui a role do apache
    include_role:
      name: geerlingguy.apache    
   
  - name: inclui a role do curso 
    include_role:
      name: curso
